travis:
  secure:
    BINSTAR_TOKEN: I2jz3cGgqx+YMHDBgwHZ1daNchOf4CKcxdUAidRliK4QjtDg+YBS6w3mJ7wmELsTB9AxtTZV0SlW3x/m0u0plDWI8/Xf8IKe/5yiJL4ERbzblBhu9u4hrqD/jNK6gSpvsaUKfR+rnK2ZL2BJX8Oz89HmQSINZatjEkvCEhp2zigUdOrVNhEZxdZNUL5r19TtwoSFBuCllVYAlWK31uSJAwYdODc+jjElL9kOPmTIGTt8pxIDiKrWNYGgn2BmAPC8OJtLLO1PKm6ojDhj0ZqrpC8p4KGVRz1w9RFdcklQs2s6i/WuuTgkMPWv0/6WKP65fwIJBzamBvPK1E1Qo4wLx2YqB06vUlw7u7lo6EryVOP6hiuuSVq9f+n4Q0zd3bk4GOIUjYbmm761ksGv5JqUA+sDrCrXicjNgAcaqN0touqxOTvLDnMUYPL+C+muBVQlFunhRefvhI56borKT9YEVX/aM/4Nlufjxh1P0SJz5Ry6Gz8SjG4AfS92372+7y34qv2STuYdhcM1x2OXY/JSetPXzayJCK+34QFDyoHJ8aKZO/HiLTqWYYtK9exa++oVVDnqrG3334sGJifiLFu0rfrX9u/dkVOgltMApAprNpMRhFfjHeVIyjqeWYnKlz3cA+zPxNMpFD8jzC3aFiGlo3hBzDJdnAlXXApQJ7P4hlE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
